import RootShifting from '@/components/shifting/root-shifting';
import { Metadata } from 'next';

export const metadata: Metadata = {
    title: 'Shifts',
    description: 'Generated by create next app',
};

export default function Dashboard() {
    return <RootShifting />;
}
